#    BVG Augenblicke Spider: read cvs file generated by json2csv.py into R 
#    Copyright (C) 2013 gitsbug
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This function will read the csv file generated by json2csv.py and return
# a data frame for further processing.
readAugenblickeCsv <- function(file) {
	if (!file.exists(file)) stop(paste(file, "doesn't exist"))

	augenblicke <- read.csv(
		file,
		colClasses=c("factor", "character", "character"),
		col.names=c("line", "spottime", "posttime")
	)

	augenblicke$line <- factor(augenblicke$line, levels(augenblicke[,1]), ordered=T)
	augenblicke$spottime <- as.POSIXct(augenblicke$spottime, format="%d.%m.%Y %H:%M")
	augenblicke$posttime <- as.POSIXct(augenblicke$posttime, format="%d.%m.%Y %H:%M")

	# The data lists the TXL express bus line to Tegel airport under two names.
	augenblicke[augenblicke$line == "JetExpressBus TXL", 1] <- "TXL"

	return(augenblicke)
}
